Awesome books: plain JavaScript with objects
oliverSCZ/awesome-books pull request #1
Opened 2021-11-30 22:00 UTC by oliverSCZ

I did the following:

- Created a GitHub repo entitled, 'awesome-books'.
- Created a new branch, 'add-javascript' from main in accordance with GitHub flow rules.
- Added all files required and followed the necessary instructions (.gitignore, .html, .css, test.md, README.md).
- Committed files (as required).
- Effectively set up a HTML & CSS & JS linter.
- Ensured that irrelevant files were ignored by Git.
- Documented my work professionally and added a descriptive README.md file to the project's repository using the template provided.
- I did that by using JavaScript objects and arrays. And also I did dynamically modifying the DOM and adding basic events.
- Opened this pull request as instructed.

2021-12-01 01:53 UTC, omar-labana requested changes
Hi @oliverSCZ, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-01 01:53 UTC, omar-labana commented on main.js
> +};
- [ ] Please make sure to clear the input field after adding a book.

2021-12-01 01:53 UTC, omar-labana commented on main.js
> +let bookList = [];
- [ ] Kindly add a default collection that has some books when first visiting the page.

2021-12-01 22:35 UTC, BrianSammit approved these changes
# STATUS: APROVED :green_circle: :clap: 

Hello @oliverSCZ, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 12:48 UTC, merged

2021-12-02 12:49 UTC, oliverSCZ commented
Thank you Mr. @omar-labana  and Mr. @BrianSammit  for your feedback and recommendations, much appreciated.